kind: pipeline
name: WHYRED KERNEL BUILD

clone:
  disable: true

steps:
- name: gnu-gcc oldcam
  image: archlinux:latest
  environment:
      TELEGRAM_TOKEN:
        from_secret: TG_BOT_API
      PERSONAL_TOKEN:
        from_secret: PAT
  commands:
    - curl https://raw.githubusercontent.com/theradcolor/lazyscripts/master/etc/workaround > workaround && bash workaround
    - pacman -Sy base-devel bc curl zip wget git lld --noconfirm
    - git clone --depth=1 --quiet https://zebusen:$PERSONAL_TOKEN@github.com/zebusen/whyred.git -b base source && cd source
    - git clone --depth=1 --quiet https://github.com/zebusen/buildscript.git
    - script -c "bash -x buildscript/sdm660.sh --gcc-elf --silont-11 --oldcam --hmp"
